In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('Demographics.csv')

In [12]:
dexcom_df = pd.read_csv('Dexcom_001.csv')
dexcom_df = dexcom_df[12:].drop(columns=['Index'])
dexcom_df['ID'] = int('001')

dexcom_df

ids = ['002', '003', '004', '005', '006', '007', '008', '009', '010', '011', '012', '013', '014', '015', '016']
for id in ids:
    temp_df = pd.read_csv(f"Dexcom_{id}.csv")
    temp_df = temp_df[12:].drop(columns=['Index'])
    temp_df['ID'] = int(id)
    dexcom_df = pd.concat([dexcom_df, temp_df], ignore_index=True)

dexcom_df = dexcom_df.rename(columns={'Timestamp (YYYY-MM-DDThh:mm:ss)': 'Timestamp'})
dexcom_df = dexcom_df.rename(columns={'Glucose Value (mg/dL)': 'Glucose'})
dexcom_df['Timestamp'] = pd.to_datetime(dexcom_df['Timestamp'], errors='coerce')
dexcom_df['Glucose'] = pd.to_numeric(dexcom_df['Glucose'], errors='coerce')

dexcom_df

,Timestamp,Event Type,Event Subtype,Patient Info,Device Info,Source Device ID,Glucose,Insulin Value (u),Carb Value (grams),Duration (hh:mm:ss),Glucose Rate of Change (mg/dL/min),Transmitter Time (Long Integer),ID
0,2020-02-13 17:23:32,EGV,NaN,NaN,NaN,iPhone G6,61.0,NaN,NaN,NaN,NaN,11101.0,1
1,2020-02-13 17:28:32,EGV,NaN,NaN,NaN,iPhone G6,59.0,NaN,NaN,NaN,NaN,11401.0,1
2,2020-02-13 17:33:32,EGV,NaN,NaN,NaN,iPhone G6,58.0,NaN,NaN,NaN,NaN,11701.0,1
3,2020-02-13 17:38:32,EGV,NaN,NaN,NaN,iPhone G6,59.0,NaN,NaN,NaN,NaN,12001.0,1
4,2020-02-13 17:43:31,EGV,NaN,NaN,NaN,iPhone G6,63.0,NaN,NaN,NaN,NaN,12301.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
36883,2020-07-24 09:58:05,EGV,NaN,NaN,NaN,iPhone G6,108.0,NaN,NaN,NaN,NaN,696577.0,16
36884,2020-07-24 10:03:05,EGV,NaN,NaN,NaN,iPhone G6,108.0,NaN,NaN,NaN,NaN,696877.0,16
36885,2020-07-24 10:08:05,EGV,NaN,NaN,NaN,iPhone G6,106.0,NaN,NaN,NaN,NaN,697177.0,16
36886,2020-07-24 10:13:05,EGV,NaN,NaN,NaN,iPhone G6,102.0,NaN,NaN,NaN,NaN,697477.0,16
36887,2020-07-24 10:18:05,EGV,NaN,NaN,NaN,iPhone G6,98.0,NaN,NaN,NaN,NaN,697777.0,16

In [4]:
food_df = pd.read_csv('Food_Log_001.csv')
food_df['ID'] = int('011')

ids = ['002', '003', '004', '005', '006', '007', '008', '009', '010', '011', '012', '013', '014', '015', '016']
for id in ids:
    temp_df = pd.read_csv(f"Food_Log_{id}.csv")
    temp_df['ID'] = int(id)
    food_df = pd.concat([food_df, temp_df], ignore_index=True)

food_df = food_df.drop(columns =['2020-02-22', '10:30:00',
       '2020-02-22 10:30:00', 'Chicken Nuggets', '8.0', 'piece',
       'Chicken Nuggets.1', '393.0', '19.0', '0.1', '20.0'], axis=1)
food_df

,date,time,time_begin,time_end,logged_food,amount,unit,searched_food,calorie,total_carb,dietary_fiber,sugar,protein,total_fat,ID,time_of_day
0,2020-02-13,18:00:00,2020-02-13 18:00:00,NaN,Berry Smoothie,20.0,fluid ounce,Strawberry Smoothie,456.0,85.0,1.7,83.0,16.0,3.3,11,NaN
1,2020-02-13,20:30:00,2020-02-13 20:30:00,NaN,Chicken Leg,1.0,NaN,chicken leg,475.0,0.0,0.0,0.0,62.0,23.0,11,NaN
2,2020-02-13,20:30:00,2020-02-13 20:30:00,NaN,Asparagus,4.0,NaN,Asparagus,13.0,2.5,1.2,0.8,1.4,0.1,11,NaN
3,2020-02-14,07:10:00,2020-02-14 07:10:00,NaN,Natrel Lactose Free 2 Percent,8.0,fluid ounce,(Natrel) Lactose Free 2% Partly Skimmed Milk,120.0,9.0,NaN,8.0,12.0,NaN,11,NaN
4,2020-02-14,07:10:00,2020-02-14 07:10:00,NaN,Standard Breakfast,0.75,cup,"(Kellogg's) Frosted Flakes, Cereal",110.0,26.0,NaN,10.0,1.0,NaN,11,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1416,2/26/2020,NaN,2020-02-26 18:30:00,NaN,Lemonade,32,oz,NaN,99.0,26.0,0.0,25.0,0.2,0.1,16,18:30
1417,2/27/2020,NaN,2020-02-27 10:30:00,NaN,Standard breakfast,NaN,NaN,NaN,280.0,56.5,1.0,24.0,8.0,2.5,16,10:30
1418,2/27/2020,NaN,2020-02-27 11:30:00,NaN,Plain cheese pizza,1,slices,NaN,452.0,57.0,3.9,6.1,19.0,16.0,16,11:30
1419,2/27/2020,NaN,2020-02-27 11:30:00,NaN,cooked black eyed peas,1,cup,NaN,198.0,35.0,11.0,5.6,13.0,0.9,16,11:30
1420,2/28/2020,NaN,2020-02-28 08:00:00,NaN,Boost,NaN,NaN,NaN,654.0,82.0,5.6,40.0,26.0,26.0,16,8:00

In [ ]:
# Convert time_begin to datetime
food_df['time_begin'] = pd.to_datetime(food_df['time_begin'], errors='coerce')

# FDA Daily Values (based on 2000 kcal diet)
daily_values = {
    'total_carb': 275,    # grams
    'protein': 50,        # grams
    'sugar': 50,          # grams
    'total_fat': 78,       # grams
    'dietary_fiber': 28   # grams
}
thresholds = {nutrient: 0.05 * dv for nutrient, dv in daily_values.items()}

# Add boolean flag columns
for nutrient, threshold in thresholds.items():
    food_df[f'{nutrient}_present'] = food_df[nutrient] >= threshold

# Preview result
#print(food_df[['ID', 'time_begin', 'logged_food', 'total_carb', 'protein', 'sugar', 'total_fat',
#               'total_carb_present', 'protein_present', 'sugar_present', 'total_fat_present']].head())
food_df

,date,time,time_begin,time_end,logged_food,amount,unit,searched_food,calorie,total_carb,...,sugar,protein,total_fat,ID,time_of_day,total_carb_present,protein_present,sugar_present,total_fat_present,dietary_fiber_present
0,2020-02-13,18:00:00,2020-02-13 18:00:00,NaN,Berry Smoothie,20.0,fluid ounce,Strawberry Smoothie,456.0,85.0,...,83.0,16.0,3.3,11,NaN,True,True,True,False,True
1,2020-02-13,20:30:00,2020-02-13 20:30:00,NaN,Chicken Leg,1.0,NaN,chicken leg,475.0,0.0,...,0.0,62.0,23.0,11,NaN,False,True,False,True,False
2,2020-02-13,20:30:00,2020-02-13 20:30:00,NaN,Asparagus,4.0,NaN,Asparagus,13.0,2.5,...,0.8,1.4,0.1,11,NaN,False,False,False,False,False
3,2020-02-14,07:10:00,2020-02-14 07:10:00,NaN,Natrel Lactose Free 2 Percent,8.0,fluid ounce,(Natrel) Lactose Free 2% Partly Skimmed Milk,120.0,9.0,...,8.0,12.0,NaN,11,NaN,False,True,True,False,False
4,2020-02-14,07:10:00,2020-02-14 07:10:00,NaN,Standard Breakfast,0.75,cup,"(Kellogg's) Frosted Flakes, Cereal",110.0,26.0,...,10.0,1.0,NaN,11,NaN,True,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1416,2/26/2020,NaN,2020-02-26 18:30:00,NaN,Lemonade,32,oz,NaN,99.0,26.0,...,25.0,0.2,0.1,16,18:30,True,False,True,False,False
1417,2/27/2020,NaN,2020-02-27 10:30:00,NaN,Standard breakfast,NaN,NaN,NaN,280.0,56.5,...,24.0,8.0,2.5,16,10:30,True,True,True,False,False
1418,2/27/2020,NaN,2020-02-27 11:30:00,NaN,Plain cheese pizza,1,slices,NaN,452.0,57.0,...,6.1,19.0,16.0,16,11:30,True,True,True,True,True
1419,2/27/2020,NaN,2020-02-27 11:30:00,NaN,cooked black eyed peas,1,cup,NaN,198.0,35.0,...,5.6,13.0,0.9,16,11:30,True,True,True,False,True
1420,2/28/2020,NaN,2020-02-28 08:00:00,NaN,Boost,NaN,NaN,NaN,654.0,82.0,...,40.0,26.0,26.0,16,8:00,True,True,True,True,True

In [22]:
# Function to filter based on selection
def get_avg_glucose_peaks(food_df, dexcom_df, selected_features, window_hrs=2):
    feature_map = {
        1: 'total_carb_present',
        2: 'protein_present',
        3: 'sugar_present',
        4: 'total_fat_present',
        5: 'dietary_fiber_present'
    }

    selected_flags = [feature_map[f] for f in selected_features if f in feature_map]
    all_flags = [col for col in food_df.columns if col.endswith('_present')]
    excluded_flags = list(set(all_flags) - set(selected_flags))

    condition_include = food_df[selected_flags].all(axis=1)
    condition_exclude = ~food_df[excluded_flags].any(axis=1)
    filtered_meals = food_df[condition_include & condition_exclude].copy()

    results = []
    for pid in filtered_meals['ID'].unique():
        meals = filtered_meals[filtered_meals['ID'] == pid]
        glucose_data = dexcom_df[dexcom_df['ID'] == pid]

        peaks = []
        for _, meal in meals.iterrows():
            start = meal['time_begin']
            end = start + pd.Timedelta(hours=2)
            window = glucose_data[(glucose_data['Timestamp'] >= start) & (glucose_data['Timestamp'] <= end)]
            if not window.empty:
                peaks.append(window['Glucose'].max())

        if peaks:
            results.append({
                'ID': pid,
                'Avg_Glucose_Peak': sum(peaks) / len(peaks),
                'Meal_Count': len(peaks)
            })

    return pd.DataFrame(results)

peaks_df = get_avg_glucose_peaks(food_df, dexcom_df, selected_features=[1,2,3,4,5])  #testing
print(peaks_df.to_string(index=False))

 ID  Avg_Glucose_Peak  Meal_Count
 11        137.500000          12
  2        163.250000           4
  4        145.333333           3
  5        132.142857           7
  6        178.260870          23
  8        146.533333          15
  9        190.000000           3
 10        198.000000           4
 12        161.125000          16
 14        158.285714           7